version: '3.3'

services:

  sipwall:
    build: .
    image: flaviostutz/sipwall
    network_mode: host
    privileged: true
    environment: 
      - LOG_LEVEL=DEBUG
      - TCPDUMP_INTERFACE=eth0
      - BAN_DENIED_TRIALS=false
      - BAN_BY_COUNTRY=true
      - ALLOWED_COUNTRIES=BR
      - BAN_TIME_SECONDS=20
      - FAIL_TIME_WINDOW_SECONDS=300
      - FAIL_COUNT_IN_WINDOW=10

  freepbx:
    image: flaviostutz/freepbx
    ports:
      - 8080:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 3306:3306
      - 18000-18100:18000-18100/udp
    restart: always
    environment:
      - MARIADB_REMOTE_ROOT_PASSWORD=admin123
      - ADMIN_PASSWORD=admin123
      - DISABLE_SIGNATURE_CHECK=true
  
